name: Tag Version (this repo)

on:
  push:
    branches:
      - release/**

jobs:
  run:
    name: Tag Version Automation
    if: github.event.pusher.name != 'github-actions[bot]'
    permissions:
      contents: 'write'
    uses: davidpuplava/GitHub-Actions/.github/workflows/tag-version.yml@release/v0.1
    with:
      called-repo-base-include-list: '@("Lombiq/GitHub-Actions")'
      additional-pattern-include-list: '@("https://raw.githubusercontent.com/Lombiq/GitHub-Actions/(?<ref>[\w\./-]*)/.github")'
    secrets:
      TAG_VERSION_TOKEN: ${{ secrets.LOMBIQBOT_GITHUB_PERSONAL_ACCESS_TOKEN }}
